theme: minima
title: Meu espaço na net!
email: eduardo.ufpb (@) gmail
description: >- # this means to ignore newlines until "baseurl:"
  Blog pessoal de Eduardo de Santana Medeiros. Desenvolvedor de software e conscienciólogo.
twitter_username: edusantana82
github_username:  edusantana

